### ISSUE TITLE
Error in accessing the databricks data 

### ISSUE THREAD

**Issue by Atul997** [databricks/databricks-sql-python#135]
I am trying to connect with the data bricks using a custom script that accesses the data in the data bricks cluster and creates a pickle file in the local system. I am getting the following error- 

    Traceback (most recent call last):
     File "Ekata_script.py", line 34, in <module>
     key, leads, lead_ids[0:], conn_odbc, "out.pkl", data
      File "/home/ubuntu/ekata/playground2/Ekata_functions.py", line 241, in Ekata_matcher_direct_address_ygl_file_odbc
       property_df, lead_df = match_all_ekata_to_properties_odbc(pull, lead_df, open_lead, conn)
      File "/home/ubuntu/ekata/playground2/Ekata_functions.py", line 408, in match_all_ekata_to_properties_odbc
      ''', con = conn)
       File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 400, in read_sql
       chunksize=chunksize)
      File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 1444, in read_query
       cursor = self.execute(*args)
      File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 1417, in execute
       raise_with_traceback(ex)
      File "/usr/lib/python3/dist-packages/pandas/compat/__init__.py", line 385, in raise_with_traceback
       raise exc.with_traceback(traceback)
      File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 1413, in execute
       self.con.rollback()
       File "/home/ubuntu/.local/lib/python3.6/site-packages/databricks/sql/client.py", line 320, in rollback
       raise NotSupportedError("Databricks does not have transactions")
      pandas.io.sql.DatabaseError: Execution failed on sql: 
                SELECT dp.property_id
                ,property_name
                ,lpa.activity_date
                ,dp.address
                ,dg.city
                ,dg.state
                ,dg.zip
                FROM table1 AS dp 
                JOIN table2 AS dg ON dp.dim_geography_key = dg.dim_geography_key
                JOIN table3 AS lpa ON lpa.property_id = dp.property_id
                AND lpa.lead_id = lead_id
                AND lpa.activity_type_code = 'RA'
                WHERE dp.latitude BETWEEN min_lat AND max_lat
                AND dp.longitude BETWEEN min_long AND max_long
                AND dp.date_end = '20991231'
                AND dg.date_end = '20991231'
                
       Query execution failed. State: ERROR_STATE; Error code: 0; SQLSTATE: 56038; Error message: 
       org.apache.hive.service.cli.HiveSQLException: Error running query: [UC_NOT_ENABLED] 
      org.apache.spark.sql.AnalysisException: [UC_NOT_ENABLED] Unity Catalog is not enabled on this cluster.
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$execute$1(SparkExecuteStatementOperation.scala:609)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

**Comment by susodapop** [comment]
Can you share the script that throws this error? It appears you are using `pandas` which we have tested and should work for your use-case.

But it seems you may not have used our built-in SQLAlchemy dialect, which knows to not emit `BEGIN TRANSACTION` statements. If you don't use the Databricks specific SQLAlchemy engine, `pandas` will try to use transactions which leads to this error.
