### ISSUE TITLE
databricks.sql.exc.RequestError: Error during request to server: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by MinuraPunchihewa** [databricks/databricks-sql-python#136]
Hi guys,
Any idea what could be causing the error given above? This is the full stack trace,
```
2023-06-03 23:44:47,664 - ERROR - Error connecting to Databricks None, Error during request to server: [Errno -3] Temporary failure in name resolution!
Traceback (most recent call last):
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/integrations/handlers/databricks_handler/databricks_handler.py", line 103, in check_connection
    self.connect()
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/integrations/handlers/databricks_handler/databricks_handler.py", line 67, in connect
    self.connection = sql.connect(
  File "/home/minura/anaconda3/envs/mindsdb_og_autosklearn/lib/python3.8/site-packages/databricks/sql/__init__.py", line 50, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
  File "/home/minura/anaconda3/envs/mindsdb_og_autosklearn/lib/python3.8/site-packages/databricks/sql/client.py", line 189, in __init__
    self._session_handle = self.thrift_backend.open_session(
  File "/home/minura/anaconda3/envs/mindsdb_og_autosklearn/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 464, in open_session
    response = self.make_request(self._client.OpenSession, open_session_req)
  File "/home/minura/anaconda3/envs/mindsdb_og_autosklearn/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 393, in make_request
    self._handle_request_error(error_info, attempt, elapsed)
  File "/home/minura/anaconda3/envs/mindsdb_og_autosklearn/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 261, in _handle_request_error
    raise network_request_error
databricks.sql.exc.RequestError: Error during request to server: [Errno -3] Temporary failure in name resolution
```
I am using `databricks-sql-connector` version 2.5.2 and Python 3.8.16.

I am trying to connect to a 10.4.x-cpu-ml-scala2.12 cluster.

**Comment by susodapop** [comment]
This happens because of some network / DNS configuration on your workstation or local network. It's not a problem `databricks-sql-connector`. You will see a similar error if you try to ping your Databricks host too. Check your VPN configuration and ensure that your DNS resolver can properly resolve Databricks URLs.
