### ISSUE TITLE
Azure Databrics, can't create a table mismatched input '(' expecting {')

### ISSUE THREAD

**Issue by bouillon** [databricks/databricks-sql-python#180]
Hi, 

SQLAlchemy==1.4.49
databricks-sql-connector==2.8.0

i have code from examples

```
import datetime
from sqlalchemy.orm import declarative_base, Session
from sqlalchemy import Column, String, Integer, BOOLEAN, create_engine, select

engine = create_engine(f"databricks://token:{access_token}@{host}?http_path={http_path}&catalog={catalog}&schema={schema}")
session  = Session(bind=engine)
base = declarative_base(bind=engine)


class SampleObject(base):

    __tablename__ = f"""mytest"""

    name = Column(String(255), primary_key=True)
    episodes = Column(Integer),
    some_bool = Column(BOOLEAN)

base.metadata.create_all()

sample_object_1 = SampleObject(name="Bim Adewunmi", episodes=6, some_bool=True)
sample_object_2 = SampleObject(name="Miki Meek", episodes=12, some_bool=False)
session.add(sample_object_1)
session.add(sample_object_2)
session.commit()

stmt = select(SampleObject).where(SampleObject.name.in_(["Bim Adewunmi", "Miki Meek"]))

output = [i for i in session.scalars(stmt)]
assert len(output) == 2

base.metadata.drop_all()
```

And get an Exeption.

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\local\docs\azure\sqlchemy_databrics.py", line 25, in <module>
    base.metadata.create_all()
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 3238, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\ddl.py", line 855, in visit_metadata
    self.traverse_single(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\ddl.py", line 899, in visit_table
    self.connection.execute(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\local\conda\envs\azure\lib\site-packages\databricks\sql\client.py", line 496, in execute
    execute_response = self.thrift_backend.execute_command(
  File "C:\local\conda\envs\azure\lib\site-packages\databricks\sql\thrift_backend.py", line 801, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "C:\local\conda\envs\azure\lib\site-packages\databricks\sql\thrift_backend.py", line 893, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "C:\local\conda\envs\azure\lib\site-packages\databricks\sql\thrift_backend.py", line 728, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(
  File "C:\local\conda\envs\azure\lib\site-packages\databricks\sql\thrift_backend.py", line 541, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.catalyst.parser.ParseException:
mismatched input '(' expecting {')', ',', 'CONSTRAINT'}(line 5, pos 13)

== SQL ==

CREATE TABLE mytest (
        name STRING NOT NULL,
        some_bool BOOLEAN,
        PRIMARY KEY (name)
-------------^^^
) USING DELTA

        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:1019)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:759)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:112)
        at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:47)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:56)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:737)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:722)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:771)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.sql.catalyst.parser.ParseException:
mismatched input '(' expecting {')', ',', 'CONSTRAINT'}(line 5, pos 13)

== SQL ==

CREATE TABLE mytest (
        name STRING NOT NULL,
        some_bool BOOLEAN,
        PRIMARY KEY (name)
-------------^^^
) USING DELTA

        at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:276)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:139)
        at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:64)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:90)
        at com.databricks.sql.parser.DatabricksSqlParser.$anonfun$parsePlan$1(DatabricksSqlParser.scala:70)
        at com.databricks.sql.parser.DatabricksSqlParser.parse(DatabricksSqlParser.scala:90)
        at com.databricks.sql.parser.DatabricksSqlParser.parsePlan(DatabricksSqlParser.scala:67)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$compileQuery$3(SparkExecuteStatementOperation.scala:845)
        at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:300)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$compileQuery$2(SparkExecuteStatementOperation.scala:845)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$compileQuery$1(SparkExecuteStatementOperation.scala:842)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.getOrCreateDF(SparkExecuteStatementOperation.scala:831)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.compileQuery(SparkExecuteStatementOperation.scala:842)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:896)
        ... 16 more

[SQL:
CREATE TABLE mytest (
        name STRING NOT NULL,
        some_bool BOOLEAN,
        PRIMARY KEY (name)
) USING DELTA

]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
Attempt to close session raised an exception at the server: Error during request to server
```

If i try to create the table with this generated syntax direct in azure notebook

```
CREATE TABLE mytest (
        name STRING NOT NULL,
        some_bool BOOLEAN,
        PRIMARY KEY (name)
) USING DELTA
```
say me

Error in SQL statement: ParseException: 
mismatched input '(' expecting {')', ',', 'CONSTRAINT'}(line 5, pos 20)

What is a problem here, is my Spark, Databrics etc to old on the azure instance and not support Primary keys?
Sorry I just make my first steps with Databrics.

**Comment by bouillon** [comment]
Follow up

i upgrade the cluster to last version

Now i get an other message 

`Error in SQL statement: DeltaAnalysisException: Table constraints are only supported in Unity Catalog.`

I have here a restriction and can't use Unity Catalog.

Is there a way to create a tables withouth PRIMARY KEYS?

**Comment by susodapop** [comment]
> I have here a restriction and can't use Unity Catalog.

Correct. Primary keys are only supported in Unity Catalog.

> Is there a way to create a tables withouth PRIMARY KEYS?

Yes, you can modify the example code to not set `primary_key=True` on the `name` column.

**Comment by bouillon** [comment]
Thats not work, because sqlalchemy requere it

```
   return fn(*args, **kwargs)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\orm\mapper.py", line 693, in __init__
    self._configure_pks()
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\orm\mapper.py", line 1400, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper mapped class SampleObject->mytest could not assemble any primary key columns for mapped table 'mytest'
```

No way to use it for me?

I found also this https://github.com/databricks/databricks-sql-python/issues/99

**Comment by susodapop** [comment]
Got it, yes you're within an edge case where you can't use SQLAlchemy ORM. Because the ORM requires a primary key. You can nevertheless use SQLAlchemy Core to manage your models. The syntax is a little different:

```python
    SampleTable = Table(
        "mytable",
        metadata_obj,
        Column("name", String(255)),
        Column("episodes", Integer),
        Column("some_bool", BOOLEAN),
        Column("dollars", DECIMAL(10, 2)),
    )
```

**Comment by bouillon** [comment]
Good to know, thanks
