### ISSUE TITLE
[Error] numpy: cannot import name 'Connection' from partially initialized module 'databricks.sql.client'

### ISSUE THREAD

**Issue by apoclyps** [databricks/databricks-sql-python#25]
### Issue

Attempting to follow the example from the [Databricks SQL Connector for Python guide
](https://docs.databricks.com/dev-tools/python-sql-connector.html) produces a circular import error.

```bash
Traceback (most recent call last):
  File "/Users/apoclyps/workspace/src/select.py", line 4, in <module>
    with sql.connect(
  File "/Users/apoclyps/.pyenv/versions/3.10.3/lib/python3.10/site-packages/databricks/sql/__init__.py", line 47, in connect
    from .client import Connection
  File "/Users/apoclyps/.pyenv/versions/3.10.3/lib/python3.10/site-packages/databricks/sql/client.py", line 8, in <module>
    import pandas
  File "/Users/apoclyps/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: cannot import name 'Connection' from partially initialized module 'databricks.sql.client' (most likely due to a circular import) (/Users/apoclyps/.pyenv/versions/3.10.3/lib/python3.10/site-packages/databricks/sql/client.py)
```

### Steps to Reproduce

```bash
pip install databricks-sql-connector==2.0.2

export DATABRICKS_SERVER_HOSTNAME="https://<redacted>.cloud.databricks.com"
export DATABRICKS_HTTP_PATH="sql/protocolv1/o/<redacted>/<redacted>"
export DATABRICKS_TOKEN="dapi<redacted>"

python main.py
```

#### contents of `main.py`:

```python
import os

from databricks import sql

with sql.connect(
    server_hostname=os.getenv("DATABRICKS_SERVER_HOSTNAME"),
    http_path=os.getenv("DATABRICKS_HTTP_PATH"),
    access_token=os.getenv("DATABRICKS_TOKEN"),
) as connection:

    with connection.cursor() as cursor:
        cursor.execute("SELECT 1")
        result = cursor.fetchall()

        for row in result:
            print(row)

```

### Additional Information

I believe the issue is caused by the following `*` import causing a circular import between `databricks.sql` and `databricks.sql.client` in [databricks/sql/client.py](https://github.com/databricks/databricks-sql-python/blob/161b94e9c7832fa8393cdff7bc9eac14f6ba840e/src/databricks/sql/client.py
)

**Comment by dbaxa** [comment]
> Our connector depends on numpy which only added support for Python 3.10 on 22 June 22 in version 1.23.0

afaik numpy added support for python 3.10 in 1.21.3 back in April of this year ->  https://numpy.org/devdocs/release/1.21.3-notes.html
> The Python versions supported in this release are 3.7-3.10. If you want to compile your own version using gcc-11, you will need to use gcc-11.2+ to avoid problems.

It seems like they had to fix a number of issues as they came up for 1.21.x though with regards to python 3.10 support (1.21.4 fixed a wheel issue for mac amd64, & 1.21.6 provides a 32 bit wheel for windows 3.10).
