### ISSUE TITLE
SQLAlchemy 2.0 support?

### ISSUE THREAD

**Issue by stuck1233333** [databricks/databricks-sql-python#91]
When I try to install it with SQLAlchemy 2.0 installed, it throws the error of: ERROR: Cannot install databricks-sql-connector==2.4.0 and sqlalchemy==2.0.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sqlalchemy==2.0.4
    databricks-sql-connector 2.4.0 depends on sqlalchemy<2.0.0 and >=1.4.44

Is there a timeline to support SQLAlchemy 2.0?

**Comment by susodapop** [comment]
We _just_ released our dialect. We will support SQLAlchemy 2.0 in a subsequent release but there's no timeline for it yet.

**Comment by josomir** [comment]
Any updates or possible timelines for this one? 
Looking forward to seeing databricks dialect supported in SQLAlchemy 2.0.

**Comment by susodapop** [comment]
We'll be working on this support in the next couple of weeks.

**Comment by rpanman-sonatype** [comment]
Excellent news, thanks!

**Comment by susodapop** [comment]
A small amount of headway on this is referenced in the discussion here: https://github.com/databricks/databricks-sql-python/pull/128

**Comment by gyandeeps** [comment]
@susodapop I was able to test out the `2.7.1.dev3` version with sqlalchemy 2 and it works great. Curious when is the planned release fore this?

**Comment by bouillon** [comment]
For me 2.7.1.dev3 not work already by create tables.

```
>>> Base.metadata.create_all(engine)

 SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class <class 'databricks.sqlalchemy.dialect.DatabricksDialect'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.
  engine = create_engine(f"databricks://token:{access_token}@{host}?http_path={http_path}&catalog={catalog}&schema={schema}", echo=True,)
2023-07-25 17:01:44,462 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-25 17:01:44,463 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 1408, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\local\docs\azure\sqlchemy_databrics.py", line 44, in <module>
    Base.metadata.create_all(engine)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\schema.py", line 5792, in create_all
    bind._run_ddl_visitor(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 3239, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\ddl.py", line 901, in visit_metadata
    [t for t in tables if self._can_create_table(t)]
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\ddl.py", line 901, in <listcomp>
    [t for t in tables if self._can_create_table(t)]
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\sql\ddl.py", line 866, in _can_create_table
    return not self.checkfirst or not self.dialect.has_table(
  File "C:\local\packages\databricks-sql-python\src\databricks\sqlalchemy\dialect\__init__.py", line 284, in has_table
    res = connection.execute(
  File "C:\local\conda\envs\azure\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'DESCRIBE TABLE hive_metastore.dbdev.test2'
Attempt to close session raised an exception at the server: Error during request to server

```

**Comment by bouillon** [comment]
What do you think, we get some more or less working pre version in some foreseeable time  for sqlalchemy 2? Don't need to be production ready but just for play around. Is it some kind of prio here? :-)

**Comment by susodapop** [comment]
@bouillon SQAlchemy will be a focus after https://github.com/databricks/databricks-sql-python/pull/182 merges. There are two primary efforts underway: implement the SQLAlchemy test suite and add support for version 2.0

**Comment by gyandeeps** [comment]
@susodapop is their any updated timeline on this effort. thanks

**Comment by mdagost** [comment]
Any updates on this?

**Comment by susodapop** [comment]
It’s in development right now. PR’s coming soon.

**Comment by sschere** [comment]
Hi Guys, do you have an estimated date to release this new version supporting SqlAlchemy 2 ?

Thanks a lot for your support on this !
