### ISSUE TITLE
Error Creating Tables - Is Databricks Unity Catalog?

### ISSUE THREAD

**Issue by ryanbales** [databricks/databricks-sql-python#99]
I'm trying to turn the [SqlAlchemy example](https://github.com/databricks/databricks-sql-python/blob/main/examples/sqlalchemy.py) from this repo on a new instance of Databricks.  

I'm getting the following error: 
> databricks.sql.exc.ServerOperationError: [UC_COMMAND_NOT_SUPPORTED] Create sample tables/views is not supported in Unity Catalog.

For context, we're not currently using the Unity Catalog. Is that required to use the latest version of the Databricks SQL Connector?

**Comment by susodapop** [comment]
While not an explicit restriction, we only test the dialect on warehouses / clusters with unity catalog enabled. Can you share which line of the example script raises this exception?

**Comment by aryanrekhi** [comment]
the error message is indicating that the specific command "Create sample tables/views" is not supported in Unity Catalog, which is a component of Databricks.

It's possible that the latest version of the Databricks SQL Connector requires the use of Unity Catalog, or at least certain functionality within it. You may want to check the documentation for the Databricks SQL Connector to see if this is the case.

If you're not currently using Unity Catalog, you may need to set it up in order to use the latest version of the connector, or you may need to use an older version of the connector that doesn't require Unity Catalog.

Alternatively, you could try modifying the example code to avoid using the unsupported command, if that's feasible for your use case.

**Comment by ryanbales** [comment]
Sorry for the delay,  I re-ran that sample again and interestingly get a different error.  Here's the full error and stack trace

>  base = declarative_base(bind=engine)
Traceback (most recent call last):
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/client.py", line 472, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 833, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 925, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 767, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 484, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
databricks.sql.exc.ServerOperationError: Table constraints are only supported in Unity Catalog.

**Comment by ryanbales** [comment]
AH I see why,  The first error was run on the following
Catalog: samples
Schema: default

The most recent error was run on:
Catalog: hive_metastore
Schema: default

**Comment by ryanbales** [comment]
Here's the trace for the initial error message

>   base = declarative_base(bind=engine)
Traceback (most recent call last):
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/client.py", line 472, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 833, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 925, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 767, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(
  File "/Users/rbales/Library/Caches/pypoetry/virtualenvs/active-ai-api-NyKgQ79e-py3.8/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 484, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
databricks.sql.exc.ServerOperationError: [UC_COMMAND_NOT_SUPPORTED] Create sample tables/views is not supported in Unity Catalog.

**Comment by susodapop** [comment]
Okay I don't see a bug here. There are two issues at play.

1) You can't create tables and views on the `samples` catalog. This catalog is there for demonstration purposes (read about it in the Databricks docs [here](https://docs.databricks.com/dbfs/databricks-datasets.html)) and is effectively read-only.

2) The error with `hive_metastore` is because that catalog is special -- it maintains backward compatibility with catalogs created before Unity Catalog was available. So although the `hive_metastore` catalog is _included in the Unity Catalog_, it doesn't have any UC features enabled. It's there purely for backward compatibility.

To move through this you need to just [create a new catalog](https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-create-catalog.html) in your UC and point SQLAlchemy at it. Many organisations simply call this catalog `main`.

**Comment by susodapop** [comment]
No UC is not required to use databricks-sql-connector.

The implicit restriction I mentioned above only applies to the SQLAlchemy dialect.

**Comment by susodapop** [comment]
That error comes directly from the cluster (i.e. it's not an issue with the python connector). Have you confirmed that UC is enabled for this cluster?

**Comment by ryanbales** [comment]
It's not, no UC is enabled.

**Comment by kravets-levko** [comment]
Hi @ryanbales! Were you able to enable UC for your cluster and check if your issue reproduces there?

**Comment by kravets-levko** [comment]
@ryanbales I'm closing this issue as stale, but if you have more questions - feel free to reopen it, or open a new one
